#!/usr/bin/env python
# encoding: utf-8

from __future__ import print_function
from haproxystat import HAProxyStat, logger

import argparse
import sys

parser = argparse.ArgumentParser(description='chess24 tool for HAProxy')
parser.add_argument('-H', '--host', help='Host to connect to (default: localhost)', default='localhost')
parser.add_argument('-p', '--port', help='Port HAProxy status listens on (default: 1936)', default='1936')
parser.add_argument('-s', '--statistic', help='Statistic to get (e.g. websocket_backend.backend.bout)')
parser.add_argument('-c', '--csv', help='Print CSV to stdout', action='store_true')
args = parser.parse_args()

try:
	haProxyStat = HAProxyStat(args.host, args.port)
	if args.csv:
		haProxyStat.printCsv()
	elif args.statistic:
		haProxyStat.printStatistic(args.statistic)
	else:
		haProxyStat.printAllStatistics()
except Exception, e:
	logger.log.exception(e)
	sys.exit(1)
